### ISSUE TITLE
Unable to select doors.

### ISSUE THREAD

**Issue by TeamQuark** [AliLogic/onset-sandbox-editor#1]
Doors cannot be selected once installed.

**Comment by AliLogic** [comment]
I'll be looking into this as soon as I get some time.

**Comment by TeamQuark** [comment]
Thank you, well done for the work.

**Comment by AliLogic** [comment]
This was fixed in this [commit](https://github.com/AliLogic/onset-sandbox-editor/commit/363f8c226e9278d921c0319e58228d86fa3d6afd).
